from pathlib import Path
import os

HOSTNAME = "127.0.0.1"
USERNAME = "efficient22"
PASSWORD = "Efficient22@123"
DATABASE = "efficient22"

PROFIT_MARGIN = 30
CONNECTED_CLIENTS = {}

# Path to the .env file used by dotenv loaders.
_ENV_PATH = Path(".env")

def set_env_path(path):
    global _ENV_PATH
    _ENV_PATH = Path(path)


def get_env_path():
    return str(_ENV_PATH)

SHOPIFY_HEADERS = [
    "Handle","Title","Body (HTML)","Vendor","Product Category","Type","Tags","Published",
    "Option1 Name","Option1 Value","Option2 Name","Option2 Value","Option3 Name","Option3 Value",
    "Variant SKU","Variant Grams","Variant Inventory Tracker","Variant Inventory Qty",
    "Variant Inventory Policy","Variant Fulfillment Service","Variant Price",
    "Variant Compare At Price","Variant Requires Shipping","Variant Taxable","Variant Barcode",
    "Image Src","Image Position","Image Alt Text","Gift Card","SEO Title","SEO Description",
    "Google Shopping / Google Product Category","Google Shopping / Gender",
    "Google Shopping / Age Group","Google Shopping / MPN","Google Shopping / Condition",
    "Google Shopping / Custom Product","Variant Image","Variant Weight Unit","Variant Tax Code",
    "Cost per item","Included / United States","Price / United States",
    "Compare At Price / United States","Included / International","Price / International",
    "Compare At Price / International","Status","Official Site Title","Official Site Description",
]

AMAZON_HEADERS = [
    "SKU",
    "Product Type",
    "Listing Action",
    "Parentage Level",
    "Parent SKU",
    "Variation Theme Name",
    "Item Name",
    "Brand Name",
    "Product Id Type",
    "Product Id",
    "Recommended Browse Nodes",
    "Recommended Browse Nodes",
    "Recommended Browse Nodes",
    "Recommended Browse Nodes",
    "Recommended Browse Nodes",
    "Target Audience",
    "Target Audience",
    "Target Audience",
    "Target Audience",
    "Target Audience",
    "Model Name",
    "Manufacturer",
    "Model Number",
    "Main Image URL",
    "Other Image URL",
    "Other Image URL",
    "Other Image URL",
    "Other Image URL",
    "Other Image URL",
    "Other Image URL",
    "Other Image URL",
    "Other Image URL",
    "Swatch Image URL",
    "Product Description",
    "Bullet Point",
    "Bullet Point",
    "Bullet Point",
    "Bullet Point",
    "Bullet Point",
    "Generic Keywords",
    "Special Features",
    "Special Features",
    "Special Features",
    "Special Features",
    "Special Features",
    "Style",
    "Department Name",
    "Target Gender",
    "Age Range Description",
    "Material",
    "Material",
    "Material",
    "Number of Items",
    "Item Type Name",
    "Special Size",
    "Color Map",
    "Color",
    "Size",
    "Metal Type",
    "Metal Type",
    "Metal Type",
    "Metal Type",
    "Metal Type",
    "Part Number",
    "Item Shape",
    "Arm Length",
    "Arm Length Unit",
    "Bridge Width",
    "Bridge Width Unit",
    "Frame Material",
    "Magnification Strength",
    "Magnification Strength Unit",
    "Polarization Type",
    "Manufacturer Contact Information",
    "Lens Color Map",
    "Lens Coating",
    "Lens Color",
    "Lens Material",
    "Lens Type",
    "Lens Width",
    "Lens Width Unit",
    "Unit Count",
    "Unit Count Type",
    "Product Site Launch Date",
    "Sport Type",
    "Sport Type",
    "League Name",
    "Team Name",
    "Athlete",
    "Ultraviolet Light Protection",
    "Recommended Uses For Product",
    "Recommended Uses For Product",
    "Recommended Uses For Product",
    "Recommended Uses For Product",
    "Recommended Uses For Product",
    "External Product Information Entity",
    "External Product Information",
    "Importer Contact Information",
    "Importer Contact Information",
    "Importer Contact Information",
    "Importer Contact Information",
    "Importer Contact Information",
    "Packer Contact Information",
    "Packer Contact Information",
    "Packer Contact Information",
    "Packer Contact Information",
    "Packer Contact Information",
    "Sunglasses Form",
    "Model Variant",
    "Inlay Material",
    "Frame Material",
    "Has Carrying Case",
    "Set Name",
    "Collection Item",
    "Is Green Purchasing Law Compliant",
    "Material",
    "Material",
    "Strap Type",
    "Strap Type",
    "Strap Type",
    "Strap Type",
    "Strap Type",
    "Pad Type",
    "Orientation",
    "Included Components",
    "Included Components",
    "Included Components",
    "Included Components",
    "Included Components",
    "Sport Type",
    "Sport Type",
    "Sport Type",
    "Hand Orientation",
    "Closure Type",
    "Closure Type",
    "Closure Type",
    "Closure Type",
    "Closure Type",
    "Number of Packs",
    "Item Diameter Circular",
    "Item Diameter Unit",
    "Construction Type",
    "Ball Type",
    "Ball Type",
    "Ball Type",
    "Ball Type",
    "Ball Type",
    "Grip Type",
    "Indoor Outdoor Usage",
    "Indoor Outdoor Usage",
    "Softball Variation",
    "Softball Variation",
    "Stitching Type",
    "Stitching Type",
    "Stitching Type",
    "Tennis Ball Duty Rating",
    "Handle Material",
    "Handle Material",
    "Skill Level",
    "Grip Material",
    "Grip Size",
    "Item Length Longer Edge",
    "Item Length Unit",
    "Item Width Shorter Edge",
    "Item Width Unit",
    "Item Length",
    "Item Length Unit",
    "Bat Drop Ratio",
    "Sport Bat Willow Type",
    "Bat Construction",
    "League Certification",
    "League Certification",
    "Bat Knob Style",
    "Swing Weight",
    "Lifestyle",
    "Lining Description",
    "Water Resistance Level",
    "Subject Character",
    "Footwear Size System",
    "Footwear Age Group",
    "Footwear Gender",
    "Footwear Size Class",
    "Footwear Width",
    "Footwear Size",
    "Footwear To Size",
    "Footwear Size System",
    "Footwear Age Group",
    "Footwear Gender",
    "Footwear Size Class",
    "Footwear Width",
    "Footwear Size",
    "Footwear To Size",
    "Occasion",
    "Occasion",
    "Occasion",
    "Occasion",
    "Occasion",
    "Theme",
    "Theme",
    "Theme",
    "Theme",
    "Theme",
    "Sole Material",
    "Toe Style",
    "Arch Type",
    "Height Map",
    "Pattern",
    "Specific Uses for Product",
    "Specific Uses for Product",
    "Specific Uses for Product",
    "Specific Uses for Product",
    "Specific Uses for Product",
    "League Name",
    "League Name",
    "League Name",
    "League Name",
    "Team Name",
    "Embellishment Feature",
    "Embellishment Feature",
    "Embellishment Feature",
    "Embellishment Feature",
    "Embellishment Feature",
    "Heel Height",
    "Heel Height Unit",
    "Heel Type",
    "Heel Type",
    "Heel Type",
    "Heel Type",
    "Insole Material",
    "Insole Material",
    "Insole Material",
    "Insole Material",
    "Insole Material",
    "Seasons",
    "Seasons",
    "Seasons",
    "Seasons",
    "Seasons",
    "Shoe Type",
    "Fit to Size Sentiment",
    "Platform Height",
    "Platform Height Unit",
    "Item Package Quantity",
    "Fit Type",
    "Care Instructions",
    "Care Instructions",
    "Care Instructions",
    "Care Instructions",
    "Design Name",
    "Glove Type",
    "Mounting Type",
    "Battery Life",
    "Battery Life Unit",
    "Skip Offer",
    "Item Condition",
    "Offer Condition Note",
    "Product Tax Code",
    "Merchant Release Date",
    "Maximum Order Quantity",
    "Offering Can Be Gift Messaged",
    "Is Gift Wrap Available",
    "Main Image Location",
    "Other Image Location",
    "Other Image Location",
    "Other Image Location",
    "Other Image Location",
    "Other Image Location",
    "Accessories",
    "Battery Life Percentage",
    "Cosmetic",
    "Features",
    "Features",
    "Features",
    "Features",
    "Features",
    "Functional Condition",
    "Packaging",
    "Source Type",
    "Import Designation",
    "Fulfillment Channel Code (IN)",
    "Quantity (IN)",
    "Handling Time (IN)",
    "Restock Date (IN)",
    "Inventory Always Available (IN)",
    "Your Price INR (Sell on Amazon, IN)",
    "Maximum Retail Price (Sell on Amazon, IN)",
    "Pricing Rule (Sell on Amazon, IN)",
    "Minimum Seller Allowed Price (Sell on Amazon, IN)",
    "Maximum Seller Allowed Price (Sell on Amazon, IN)",
    "Sale Price INR (Sell on Amazon, IN)",
    "Sale Start Date (Sell on Amazon, IN)",
    "Sale End Date (Sell on Amazon, IN)",
    "Offering Release Date (Sell on Amazon, IN)",
    "Stop Selling Date (Sell on Amazon, IN)",
    "Shipping Template (IN)",
    "Item Length",
    "Item Length Unit",
    "Item Width",
    "Item Width Unit",
    "Item Height",
    "Item Height Unit",
    "Item Package Length",
    "Package Length Unit",
    "Item Package Width",
    "Package Width Unit",
    "Item Package Height",
    "Package Height Unit",
    "Package Weight",
    "Package Weight Unit",
    "Number of Boxes",
    "Country of Origin",
    "Are batteries required?",
    "Are batteries included?",
    "Battery Cell Composition",
    "Battery Cell Composition Other Than Listed",
    "Battery IEC Code",
    "Battery Weight",
    "Battery Weight Unit",
    "Number of Batteries",
    "Battery Type",
    "Number of Lithium Metal Cells",
    "Number of Lithium-ion Cells",
    "Lithium Battery Energy Content",
    "Lithium Battery Energy Content Unit",
    "Lithium Battery Packaging",
    "Lithium Battery Weight",
    "Lithium Battery Weight Unit",
    "Dangerous Goods Regulations",
    "Dangerous Goods Regulations",
    "Dangerous Goods Regulations",
    "Dangerous Goods Regulations",
    "Dangerous Goods Regulations",
    "GHS Class",
    "GHS Class",
    "GHS Class",
    "GHS Class",
    "GHS Class",
    "Hazmat Aspect",
    "Hazmat",
    "Safety Data Sheet (SDS or MSDS) URL",
    "Item Weight",
    "Item Weight Unit",
    "Is This Product Subject To Buyer Age Restrictions",
    "Compliance Regulation Type",
    "Regulatory Identification",
    "Compliance Regulation Type",
    "Regulatory Identification",
    "Compliance Regulation Type",
    "Regulatory Identification",
    "Compliance Regulation Type",
    "Regulatory Identification",
    "Compliance Regulation Type",
    "Regulatory Identification",
    "Responsible Person's Email or Electronic Address",
    "Compliance Media Source Location (en_IN, Application Guide)",
    "Compliance Media Source Location (en_IN, Certificate of Analysis)",
    "Compliance Media Source Location (en_IN, Certificate of Compliance)",
    "Compliance Media Source Location (en_IN, Compatibility Guide)",
    "Compliance Media Source Location (en_IN, Data Act Transparency Declaration)",
    "Compliance Media Source Location (en_IN, Emergency Use Authorization)",
    "Compliance Media Source Location (en_IN, Emergency Use Authorization Amendment)",
    "Compliance Media Source Location (en_IN, Installation Manual)",
    "Compliance Media Source Location (en_IN, Instructions for Use)",
    "Compliance Media Source Location (en_IN, Patient Fact Sheet)",
    "Compliance Media Source Location (en_IN, Product Certificate of Conformity)",
    "Compliance Media Source Location (en_IN, Provider Fact Sheet)",
    "Compliance Media Source Location (en_IN, Safety Data Sheet)",
    "Compliance Media Source Location (en_IN, Safety Information)",
    "Compliance Media Source Location (en_IN, Specification Sheet)",
    "Compliance Media Source Location (en_IN, Troubleshooting Guide)",
    "Compliance Media Source Location (en_IN, User Guide)",
    "Compliance Media Source Location (en_IN, User Manual)",
    "Compliance Media Source Location (en_IN, Warranty)",
    "Safety Attestation",
    "Manufacturer’s Email or Electronic Address",
    "Has Multiple Battery Powered Components",
    "Ships Globally",
    "Contains Battery or Cell",
    "Battery Contains free Unabsorbed Liquid",
    "Is Battery Non Spillable",
    "Non-Lithium Battery Packaging",
    "Has Replaceable Battery",
    "Non-Lithium Battery Energy Content",
    "Non-Lithium Battery Energy Content Unit",
    "Has Less than 30 Percent State of Charge",
    "Battery Installation Device Type",
    "Is OEM Sourced Product",
    "GHS Chemical H Code",
    "GHS Chemical H Code",
    "GHS Chemical H Code",
    "GHS Chemical H Code",
    "GHS Chemical H Code",
    "Warranty Description",
    "Warranty Description",
    "Warranty Description",
    "Warranty Description",
    "Warranty Description",
    "Number of Batteries",
    "Battery Type",
    "Number of Batteries",
    "Battery Type",
    "Number of Batteries",
    "Battery Type",
    "Number of Batteries",
    "Battery Type",
    "Base Product Manufacturer Warranty Period",
    "Base Product Warranty Manufacturer Period Unit",
    "Base Product Manufacturer Warranty Terms and Conditions",
    "Steps To Avail Warranty",
    "Warranty Provider Contact Information",
    "Value",
    "Item Weight Unit",
    "Outer Material",
    "Outer Material",
    "Outer Material",
    "Outer Material",
    "Outer Material",
    "Compliance - Diameter",
    "Compliance - Ball Sport Type",
    "Compliance - Ball Structure",
    "Compliance - Ball Type",
    "Fur Description",
    "Compliance - Upper Height",
    "Compliance - Upper Manufacturing Process",
    "Compliance - Upper Material",
    "Compliance - Upper Textile Material",
    "Compliance - Upper Weave Design",
    "Compliance - Waterproof Footwear Type",
    "Compliance - Footwear Coating Material",
    "Compliance - Height Map",
    "Compliance - Inner Sole Material",
    "Compliance - Shoe Special Feature",
    "Compliance - Shoe Type",
    "Compliance - Is Disposable",
    "Compliance - Sole Construction Type",
    "Compliance - Is Handmade",
    "Compliance - Sole Material",
    "Compliance - Toe Style",
    "Compliance - Age Range",
    "Compliance - Band Application",
    "Compliance - Upper Textile Coverage",
    "Compliance - Upper Textile Grammage",
    "Inner Material"
]

FLIPKART_HEADERS = [
    "Flipkart Serial Number", "Catalog QC Status", "QC Failed Reason (if any)", "Flipkart Product Link", "Product Data Status", 
    "Disapproval Reason (if any)", "Seller SKU ID", "Group ID", "Listing Status", "MRP (INR)", "Your selling price (INR)", 
    "Fullfilment by", "Procurement type", "Procurement SLA (DAY)", "Stock", "Shipping provider", "Local handling fee (INR)", 
    "Zonal handling fee (INR)", "National handling fee (INR)", "Length (CM)", "Breadth (CM)", "Height (CM)", "Weight (KG)", "HSN", 
    "Luxury Cess", "Country Of Origin", "Manufacturer Details", "Packer Details", "Importer Details", "Tax Code", "Minimum Order Quantity (MinOQ)", 
    "Brand", "Blade Material", "Sport Type", "Cover Included", "Model Name", "Weight Range", "Weight Range - Measuring Unit", "Part Number", 
    "Size", "Playing Level", "Age Group", "Ideal For", "Color", "Width", "Width - Measuring Unit", "Height", "Height - Measuring Unit", 
    "Depth", "Depth - Measuring Unit", "Bat Grade", "Main Image URL", "Other Image URL 1", "Other Image URL 2", "Other Image URL 3", 
    "Other Image URL 4", "Items Included", "Pack of", "Series", "Curve", "Designed For", "Suitable For", "Anti-Scuff Sheet", "Toe Guard", 
    "Certification", "Barrell Material", "End Cap Material", "End Cap", "Handle Type", "Handle Grip Type", "Handle Material", "Other Body Features", 
    "Blade Width (inch)", "Blade Height (inch)", "Handle Length (inch)", "Handle Diameter (inch)", "Baseball Bat Diameter (inch)", "Other Features", 
    "Description", "Search Keywords", "Key Features", "Video URL", "Domestic Warranty", "Domestic Warranty - Measuring Unit", "International Warranty",
    "International Warranty - Measuring Unit", "Warranty Summary", "Warranty Service Type", "Covered in Warranty", "Not Covered in Warranty", "EAN/UPC"
]